### ISSUE TITLE
Command `create` doesn't set Authorization header when token is informed.

### ISSUE THREAD

**Issue by ingoncalves** [panva/openid-client-cli#2]
According with the Dynamic Client Registration spec (http://openid.net/specs/openid-connect-registration-1_0.html), the registration endpoint could need an initial access token to protect it.
In the `usage`, this feature was planned but it does not work.

    Usage: openid-client-create [options] <registration_endpoint> [properties...]

    Options:

    -t, --token [value]  use as value initial access token

When I set the token, like:
    
    $ openid-client create -t foo https://op.example.com/client/register redirect_uris=https://lvh.me:3000/cb client_name=Foobar

the `Authorization` header is not setted.

**Comment by panva** [comment]
Thank you for noticing, i merged your PR and published a patch version.
